# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hi": "00_core.ipynb"}

modules = ["hi.py"]

doc_url = "https://juansensio.github.io/nangs/"

git_url = "https://github.com/juansensio/nangs/tree/master/"

def custom_doc_links(name): return None
