# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"checkIsListOfStr": "00_utils.ipynb",
         "checkUnique": "00_utils.ipynb",
         "initListOfStr": "00_utils.ipynb",
         "PDE": "01_pde.ipynb"}

modules = ["utils.py",
           "pde.py"]

doc_url = "https://juansensio.github.io/nangs/"

git_url = "https://github.com/juansensio/nangs/tree/master/"

def custom_doc_links(name): return None
