# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PDEDataset": "00_pde.ipynb",
         "PDE": "00_pde.ipynb",
         "Boco": "01_bocos.ipynb",
         "PeriodicBocoDataset": "01_bocos.ipynb",
         "PeriodicBoco": "01_bocos.ipynb",
         "DirichletBocoDataset": "01_bocos.ipynb",
         "DirichletBoco": "01_bocos.ipynb",
         "NeumannBocoDataset": "01_bocos.ipynb",
         "NeumannBoco": "01_bocos.ipynb",
         "Solution": "02_solution.ipynb",
         "getActivation": "02_solution.ipynb",
         "block": "02_solution.ipynb",
         "checkIsListOfStr": "09_utils.ipynb",
         "checkUnique": "09_utils.ipynb",
         "checkNoRepeated": "09_utils.ipynb",
         "checkValidArray": "09_utils.ipynb",
         "checkValidDict": "09_utils.ipynb",
         "checkDictArray": "09_utils.ipynb"}

modules = ["pde.py",
           "bocos.py",
           "solution.py",
           "utils.py"]

doc_url = "https://juansensio.github.io/nangs/"

git_url = "https://github.com/juansensio/nangs/tree/master/"

def custom_doc_links(name): return None
