# AUTOGENERATED! DO NOT EDIT! File to edit: 01_pde.ipynb (unless otherwise specified).

__all__ = ['PDE']

# Cell

class PDE:
    "PDE class with basic functionality to solve PDEs with NNs"
    def __init__(self, inputs, outputs, params=None):

        self.inputs = inputs
        self.outputs = outputs
        self.params = params

        # initialize values
        self.inputTrainValues = initListOfStr(self.inputs)
        self.inputValValues = initListOfStr(self.inputs)
        self.inputTestValues = initListOfStr(self.inputs)
        self.outputValues = initListOfStr(self.outputs)
        self.paramValues = None
        if self.params:
            self.paramValues = initListOfStr(self.params)

        self.bocos = []

    def summary(self):
        "Print a summary of the PDE inputs, outputs, params and bocos."
        print('inputs (train): ', {name: values for name, values in zip(self.inputs, self.inputTrainValues)})
        print('inputs (val): ', {name: values for name, values in zip(self.inputs, self.inputValValues)})
        print('outputs: ', {name: values for name, values in zip(self.outputs, self.outputValues)})
        print('params: ', {name: values for name, values in zip(self.params, self.paramValues)})
        print('bocos: ', [boco.type for boco in self.bocos])
        print('')