# AUTOGENERATED! DO NOT EDIT! File to edit: 00_utils.ipynb (unless otherwise specified).

__all__ = ['checkIsListOfStr', 'checkUnique', 'initListOfStr']

# Cell
def checkIsListOfStr(l):
    if not isinstance(l, list):
        raise Exception(str(l) + ' must be a list of strings')
    for i in l:
        if not isinstance(i, str):
            raise Exception(str(i) + ' must be a string')

# Cell
def checkUnique(l):
    for i, item1 in enumerate(l):
        for j, item2 in enumerate(l):
            if i != j and item1 == item2:
                raise Exception('Repeated item ' + str(item1))

# Cell
def initListOfStr(l):
    "Receives a list of unique strings and returns an empty list for each item"
    checkIsListOfStr(l)
    checkUnique(l)
    return [[] for i in l]