# AUTOGENERATED! DO NOT EDIT! File to edit: 00_utils.ipynb (unless otherwise specified).

__all__ = ['initStringList']

# Cell
def initStringList(l):
    "Receives a list of unique strings and returns an empty list for each item"
    # TODO: assert l is a list of strings
    # TODO: assert l does not contain repeated values
    return [[] for i in l]